title: The Trippy Frog | Adventures & Tours in the Himalayas
name: The Trippy Frog
email: thetrippyfrog@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Outdoor Adventure Activities in the Himalayas full of fun, thrill and a rush of adrenaline | Rafting, Paragliding, Camping, Trekking, Bike-Tours, Trekking.
baseurl: ''
url: 'https://thetrippyfrog.com'

permalink: slug

collections:
  activities:
    output: true
    permalink: /:title
    include: app-assets
  escape:
    output: true
    permalink: /:title
    include: app-assets
  packages:
    output: false
    permalink: /:title
    include: app-assets
  treks:
    output: true
    permalink: /:title
    include: app-assets
  camping:
    output: true
    permalink: /:title
    include: app-assets
  legal:
    output: true
    permalink: /:title
    include: app-assets
  renting:
    output: false
    permalink: /:title
    include: app-assets

defaults:
  - scope:
      path: ''
      type: 'activities'
    values:
      layout: 'default'
      image: true
      type: 'activities'

exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
  - license
  - CNAME
plugins:
  - jekyll-sitemap
strict_front_matter: true